#ifndef RESULTSDOCKWIDGET_H
#define RESULTSDOCKWIDGET_H

#include <QDockWidget>
#include <QTabWidget>


class ResultsDockWidget : public QDockWidget
{
    Q_OBJECT
    Q_DISABLE_COPY(ResultsDockWidget)
public:
    explicit ResultsDockWidget(QWidget* parent = nullptr, Qt::WindowFlags flags = 0);
protected:
  /// Manages the tabs for output generated by build and debug tools
  QTabWidget* resultsTabWidget;
};

#endif // RESULTSDOCKWIDGET_H
