#ifndef RESULTSDOCKWIDGET_H
#define RESULTSDOCKWIDGET_H

#include <QDockWidget>
#include <QListWidget>
#include <QTabWidget>
#include <QTextEdit>


class ResultsDockWidget : public QDockWidget
{
    Q_OBJECT
    Q_DISABLE_COPY(ResultsDockWidget)
public:
    explicit ResultsDockWidget(QWidget* parent = nullptr, Qt::WindowFlags flags = 0);

protected:
  /// Manages the tabs for output generated by build and debug tools
  QTabWidget* resultsTabWidget;
  QTextEdit* compilerOutputTab;
  /// A control to display compiler, linker and debugger output
  QListWidget* toolsOutput;
//  /// Let user compare differences between test case's input/output/error and his/her solution
//  StandardInputOutpInspector* standardInputOutputInspector = nullptr;
};

#endif // RESULTSDOCKWIDGET_H
